# Generated by Django 4.2.16 on 2024-10-09 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meetingroom',
            options={'verbose_name': '미팅룸 관리', 'verbose_name_plural': '미팅룸 관리'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': '관리자 관리', 'verbose_name_plural': '관리자 관리'},
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '얘약 관리', 'verbose_name_plural': '얘약 관리'},
        ),
    ]
