# Generated by Django 4.2.16 on 2024-10-09 05:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_app', '0002_alter_meetingroom_options_alter_profile_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '예약 관리', 'verbose_name_plural': '예약 관리'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.CharField(max_length=100, verbose_name='회사명'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='company_contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='회사 연락처'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='manager_contact',
            field=models.CharField(max_length=20, verbose_name='담당자 연락처'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='manager_name',
            field=models.CharField(max_length=100, verbose_name='담당자 이름'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='직책'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', '관리자'), ('superadmin', '슈퍼어드민')], max_length=20, verbose_name='역할'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
    ]
