# Generated by Django 4.2.16 on 2024-10-15 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_hotel_delete_reservation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hotel',
        ),
    ]
