# Generated by Django 4.2.16 on 2024-10-16 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_hotel_detail_address_hotel_postal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='business_number',
            field=models.CharField(default='123-45-67890', max_length=12, verbose_name='사업자 번호'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='hotel_logos/', verbose_name='호텔 로고 이미지'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='settlement_date',
            field=models.CharField(choices=[('', '선택'), ('익월 1일', '익월 1일'), ('익월 5일', '익월 5일'), ('익월 10일', '익월 10일'), ('익월 15일', '익월 15일'), ('익월 20일', '익월 20일'), ('익월 25일', '익월 25일'), ('익월 30일', '익월 30일')], default='', max_length=10, verbose_name='정산일'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='postal_code',
            field=models.CharField(default='우편번호 5자리', max_length=5, verbose_name='우편번호'),
        ),
    ]
