# Generated by Django 4.2.16 on 2024-10-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_hotel_business_number_hotel_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='business_number',
            field=models.CharField(default='사업자번호를 입력하세요 (예시) 123-45-67890', max_length=12, verbose_name='사업자 번호'),
        ),
    ]
